

export const studyLevels = [
  { value: 'btech', label: 'B.Tech' },
  { value: 'mtech', label: 'M.Tech' },
  { value: 'mba', label: 'MBA' },
  { value: 'diploma', label: 'Diploma' },
  { value: 'bsc', label: 'B.Sc' },
  { value: 'msc', label: 'M.Sc' },
  { value: 'bcom', label: 'B.Com' },
  { value: 'mcom', label: 'M.Com' },
  { value: 'ba', label: 'B.A' },
  { value: 'ma', label: 'M.A' },
  { value: 'bca', label: 'BCA' },
  { value: 'mca', label: 'MCA' },
  { value: 'bba', label: 'BBA' },
  { value: 'phd', label: 'Ph.D' },
];

const engineeringCourses = [
    { value: 'computer-science-engineering', label: 'Computer Science & Engineering' },
    { value: 'mechanical-engineering', label: 'Mechanical Engineering' },
    { value: 'electronics-communication-engineering', label: 'Electronics & Communication Engineering' },
    { value: 'civil-engineering', label: 'Civil Engineering' },
    { value: 'information-technology', label: 'Information Technology' },
    { value: 'electrical-engineering', label: 'Electrical Engineering' },
    { value: 'aerospace-engineering', label: 'Aerospace Engineering' },
    { value: 'chemical-engineering', label: 'Chemical Engineering' },
    { value: 'biotechnology-engineering', label: 'Biotechnology Engineering' },
    { value: 'automobile-engineering', label: 'Automobile Engineering' },
];

const managementCourses = [
    { value: 'marketing', label: 'Marketing' },
    { value: 'finance', label: 'Finance' },
    { value: 'human-resources', label: 'Human Resources' },
    { value: 'business-analytics', label: 'Business Analytics' },
    { value: 'operations-management', label: 'Operations Management' },
];

const scienceCourses = [
    { value: 'physics', label: 'Physics' },
    { value: 'chemistry', label: 'Chemistry' },
    { value: 'mathematics', label: 'Mathematics' },
    { value: 'biotechnology', label: 'Biotechnology' },
];

const commerceCourses = [
    { value: 'accounting-finance', label: 'Accounting and Finance' },
    { value: 'banking-insurance', label: 'Banking and Insurance' },
    { value: 'taxation', label: 'Taxation' },
];

const artsCourses = [
    { value: 'history', label: 'History' },
    { value: 'political-science', label: 'Political Science' },
    { value: 'economics', label: 'Economics' },
    { value: 'sociology', label: 'Sociology' },
];

const computerApplicationCourses = [
    { value: 'web-development', label: 'Web Development' },
    { value: 'mobile-app-development', label: 'Mobile Application Development' },
    { value: 'data-science-analytics', label: 'Data Science & Analytics' },
];

export const courses: Record<string, { value: string; label: string }[]> = {
    btech: engineeringCourses,
    mtech: engineeringCourses,
    diploma: engineeringCourses,
    phd: [...engineeringCourses, ...scienceCourses, ...artsCourses, ...managementCourses],
    mba: managementCourses,
    bba: managementCourses,
    bsc: scienceCourses,
    msc: scienceCourses,
    bcom: commerceCourses,
    mcom: commerceCourses,
    ba: artsCourses,
    ma: artsCourses,
    bca: computerApplicationCourses,
    mca: computerApplicationCourses,
};


export const specializations: Record<string, { value: string; label: string }[]> = {
  'computer-science-engineering': [
    { value: 'ai-ml', label: 'Artificial Intelligence and Machine Learning' },
    { value: 'data-science', label: 'Data Science' },
    { value: 'cyber-security', label: 'Cyber Security' },
    { value: 'robotics-automation', label: 'Robotics and Automation' },
    { value: 'software-engineering', label: 'Software Engineering' },
    { value: 'blockchain', label: 'Blockchain Technology' },
    { value: 'iot', label: 'Internet of Things (IoT)' },
  ],
  'mechanical-engineering': [
    { value: 'robotics-automation', label: 'Robotics and Automation' },
    { value: 'mechatronics-engineering', label: 'Mechatronics Engineering' },
    { value: 'thermal-engineering', label: 'Thermal Engineering' },
    { value: 'manufacturing-engineering', label: 'Manufacturing Engineering' },
    { value: 'automobile-engineering', label: 'Automobile Engineering' },
  ],
  'electronics-communication-engineering': [
    { value: 'vlsi-design', label: 'VLSI Design' },
    { value: 'communication-systems', label: 'Communication Systems' },
    { value: 'iot', label: 'Internet of Things (IoT)' },
    { value: 'embedded-systems', label: 'Embedded Systems' },
  ],
  'civil-engineering': [
    { value: 'structural-engineering', label: 'Structural Engineering' },
    { value: 'transportation-engineering', label: 'Transportation Engineering' },
    { value: 'environmental-engineering', label: 'Environmental Engineering' },
    { value: 'construction-engineering', label: 'Construction Engineering' },
  ],
  'information-technology': [
    { value: 'cyber-security', label: 'Cyber Security' },
    { value: 'data-science', label: 'Data Science' },
    { value: 'cloud-computing', label: 'Cloud Computing' },
    { value: 'network-security', label: 'Network Security' },
  ],
  'electrical-engineering': [
    { value: 'power-systems', label: 'Power Systems' },
    { value: 'renewable-energy', label: 'Renewable Energy' },
    { value: 'power-electronics', label: 'Power Electronics' },
  ],
   marketing: [
    { value: 'digital-marketing', label: 'Digital Marketing' },
    { value: 'strategic-management', label: 'Strategic Management' },
    { value: 'market-research', label: 'Market Research' },
  ],
  finance: [
    { value: 'investment-banking', label: 'Investment Banking' },
    { value: 'corporate-finance', label: 'Corporate Finance' },
    { value: 'fintech', label: 'Financial Technology (FinTech)' },
  ],
  'human-resources': [
    { value: 'talent-management', label: 'Talent Management' },
    { value: 'organizational-behavior', label: 'Organizational Behavior' },
  ],
   physics: [
    { value: 'astrophysics', label: 'Astrophysics' },
    { value: 'quantum-mechanics', label: 'Quantum Mechanics' },
    { value: 'nuclear-physics', label: 'Nuclear Physics' },
  ],
  chemistry: [
    { value: 'organic-chemistry', label: 'Organic Chemistry' },
    { value: 'analytical-chemistry', label: 'Analytical Chemistry' },
  ],
  'web-development': [
    {value: 'full-stack-development', label: 'Full-Stack Development'},
    {value: 'frontend-development', label: 'Frontend Development'},
    {value: 'backend-development', label: 'Backend Development'},
  ]
};

export const languages = [
  { value: 'en', label: 'English' },
  { value: 'es', label: 'Español' },
  { value: 'fr', label: 'Français' },
  { value: 'de', label: 'Deutsch' },
  { value: 'zh', label: '中文 (Mandarin)' },
  { value: 'hi', label: 'हिन्दी (Hindi)' },
  { value: 'ar', label: 'العربية (Arabic)' },
  { value: 'bn', label: 'বাংলা (Bengali)' },
  { value: 'pt', label: 'Português' },
  { value: 'ru', label: 'Русский (Russian)' },
  { value: 'ja', label: '日本語 (Japanese)' },
  { value: 'jv', label: 'Basa Jawa (Javanese)' },
  { value: 'ko', label: '한국어 (Korean)' },
  { value: 'vi', label: 'Tiếng Việt (Vietnamese)' },
  { value: 'te', label: 'తెలుగు (Telugu)' },
  { value: 'mr', label: 'मराठी (Marathi)' },
  { value: 'tr', label: 'Türkçe (Turkish)' },
  { value: 'ta', label: 'தமிழ் (Tamil)' },
  { value: 'ur', label: 'اردو (Urdu)' },
  { value: 'gu', label: 'ગુજરાતી (Gujarati)' },
  { value: 'pl', label: 'Polski (Polish)' },
  { value: 'uk', label: 'Українська (Ukrainian)' },
  { value: 'it', label: 'Italiano (Italian)' },
  { value: 'ro', label: 'Română (Romanian)' },
  { value: 'nl', label: 'Nederlands (Dutch)' },
];

export const countries = [
  { value: "af", label: "Afghanistan" },
  { value: "ax", label: "Aland Islands" },
  { value: "al", label: "Albania" },
  { value: "dz", label: "Algeria" },
  { value: "as", label: "American Samoa" },
  { value: "ad", label: "Andorra" },
  { value: "ao", label: "Angola" },
  { value: "ai", label: "Anguilla" },
  { value: "aq", label: "Antarctica" },
  { value: "ag", label: "Antigua and Barbuda" },
  { value: "ar", label: "Argentina" },
  { value: "am", label: "Armenia" },
  { value: "aw", label: "Aruba" },
  { value: "au", label: "Australia" },
  { value: "at", label: "Austria" },
  { value: "az", label: "Azerbaijan" },
  { value: "bs", label: "Bahamas" },
  { value: "bh", label: "Bahrain" },
  { value: "bd", label: "Bangladesh" },
  { value: "bb", label: "Barbados" },
  { value: "by", label: "Belarus" },
  { value: "be", label: "Belgium" },
  { value: "bz", label: "Belize" },
  { value: "bj", label: "Benin" },
  { value: "bm", label: "Bermuda" },
  { value: "bt", label: "Bhutan" },
  { value: "bo", label: "Bolivia" },
  { value: "bq", label: "Bonaire, Sint Eustatius and Saba" },
  { value: "ba", label: "Bosnia and Herzegovina" },
  { value: "bw", label: "Botswana" },
  { value: "bv", label: "Bouvet Island" },
  { value: "br", label: "Brazil" },
  { value: "io", label: "British Indian Ocean Territory" },
  { value: "bn", label: "Brunei Darussalam" },
  { value: "bg", label: "Bulgaria" },
  { value: "bf", label: "Burkina Faso" },
  { value: "bi", label: "Burundi" },
  { value: "kh", label: "Cambodia" },
  { value: "cm", label: "Cameroon" },
  { value: "ca", label: "Canada" },
  { value: "cv", label: "Cape Verde" },
  { value: "ky", label: "Cayman Islands" },
  { value: "cf", label: "Central African Republic" },
  { value: "td", label: "Chad" },
  { value: "cl", label: "Chile" },
  { value: "cn", label: "China" },
  { value: "cx", label: "Christmas Island" },
  { value: "cc", label: "Cocos (Keeling) Islands" },
  { value: "co", label: "Colombia" },
  { value: "km", label: "Comoros" },
  { value: "cg", label: "Congo" },
  { value: "cd", label: "Congo, Democratic Republic of the" },
  { value: "ck", label: "Cook Islands" },
  { value: "cr", label: "Costa Rica" },
  { value: "ci", label: "Cote D'Ivoire" },
  { value: "hr", label: "Croatia" },
  { value: "cu", label: "Cuba" },
  { value: "cw", label: "Curaçao" },
  { value: "cy", label: "Cyprus" },
  { value: "cz", label: "Czech Republic" },
  { value: "dk", label: "Denmark" },
  { value: "dj", label: "Djibouti" },
  { value: "dm", label: "Dominica" },
  { value: "do", label: "Dominican Republic" },
  { value: "ec", label: "Ecuador" },
  { value: "eg", label: "Egypt" },
  { value: "sv", label: "El Salvador" },
  { value: "gq", label: "Equatorial Guinea" },
  { value: "er", label: "Eritrea" },
  { value: "ee", label: "Estonia" },
  { value: "et", label: "Ethiopia" },
  { value: "fk", label: "Falkland Islands (Malvinas)" },
  { value: "fo", label: "Faroe Islands" },
  { value: "fj", label: "Fiji" },
  { value: "fi", label: "Finland" },
  { value: "fr", label: "France" },
  { value: "gf", label: "French Guiana" },
  { value: "pf", label: "French Polynesia" },
  { value: "tf", label: "French Southern Territories" },
  { value: "ga", label: "Gabon" },
  { value: "gm", label: "Gambia" },
  { value: "ge", label: "Georgia" },
  { value: "de", label: "Germany" },
  { value: "gh", label: "Ghana" },
  { value: "gi", label: "Gibraltar" },
  { value: "gr", label: "Greece" },
  { value: "gl", label: "Greenland" },
  { value: "gd", label: "Grenada" },
  { value: "gp", label: "Guadeloupe" },
  { value: "gu", label: "Guam" },
  { value: "gt", label: "Guatemala" },
  { value: "gg", label: "Guernsey" },
  { value: "gn", label: "Guinea" },
  { value: "gw", label: "Guinea-Bissau" },
  { value: "gy", label: "Guyana" },
  { value: "ht", label: "Haiti" },
  { value: "hm", label: "Heard Island and Mcdonald Islands" },
  { value: "va", label: "Holy See (Vatican City State)" },
  { value: "hn", label: "Honduras" },
  { value: "hk", label: "Hong Kong" },
  { value: "hu", label: "Hungary" },
  { value: "is", label: "Iceland" },
  { value: "in", label: "India" },
  { value: "id", label: "Indonesia" },
  { value: "ir", label: "Iran, Islamic Republic of" },
  { value: "iq", label: "Iraq" },
  { value: "ie", label: "Ireland" },
  { value: "im", label: "Isle of Man" },
  { value: "il", label: "Israel" },
  { value: "it", label: "Italy" },
  { value: "jm", label: "Jamaica" },
  { value: "jp", label: "Japan" },
  { value: "je", label: "Jersey" },
  { value: "jo", label: "Jordan" },
  { value: "kz", label: "Kazakhstan" },
  { value: "ke", label: "Kenya" },
  { value: "ki", label: "Kiribati" },
  { value: "kp", label: "Korea, Democratic People's Republic of" },
  { value: "kr", label: "Korea, Republic of" },
  { value: "xk", label: "Kosovo" },
  { value: "kw", label: "Kuwait" },
  { value: "kg", label: "Kyrgyzstan" },
  { value: "la", label: "Lao People's Democratic Republic" },
  { value: "lv", label: "Latvia" },
  { value: "lb", label: "Lebanon" },
  { value: "ls", label: "Lesotho" },
  { value: "lr", label: "Liberia" },
  { value: "ly", label: "Libyan Arab Jamahiriya" },
  { value: "li", label: "Liechtenstein" },
  { value: "lt", label: "Lithuania" },
  { value: "lu", label: "Luxembourg" },
  { value: "mo", label: "Macao" },
  { value: "mk", label: "Macedonia, the Former Yugoslav Republic of" },
  { value: "mg", label: "Madagascar" },
  { value: "mw", label: "Malawi" },
  { value: "my", label: "Malaysia" },
  { value: "mv", label: "Maldives" },
  { value: "ml", label: "Mali" },
  { value: "mt", label: "Malta" },
  { value: "mh", label: "Marshall Islands" },
  { value: "mq", label: "Martinique" },
  { value: "mr", label: "Mauritania" },
  { value: "mu", label: "Mauritius" },
  { value: "yt", label: "Mayotte" },
  { value: "mx", label: "Mexico" },
  { value: "fm", label: "Micronesia, Federated States of" },
  { value: "md", label: "Moldova, Republic of" },
  { value: "mc", label: "Monaco" },
  { value: "mn", label: "Mongolia" },
  { value: "me", label: "Montenegro" },
  { value: "ms", label: "Montserrat" },
  { value: "ma", label: "Morocco" },
  { value: "mz", label: "Mozambique" },
  { value: "mm", label: "Myanmar" },
  { value: "na", label: "Namibia" },
  { value: "nr", label: "Nauru" },
  { value: "np", label: "Nepal" },
  { value: "nl", label: "Netherlands" },
  { value: "an", label: "Netherlands Antilles" },
  { value: "nc", label: "New Caledonia" },
  { value: "nz", label: "New Zealand" },
  { value: "ni", label: "Nicaragua" },
  { value: "ne", label: "Niger" },
  { value: "ng", label: "Nigeria" },
  { value: "nu", label: "Niue" },
  { value: "nf", label: "Norfolk Island" },
  { value: "mp", label: "Northern Mariana Islands" },
  { value: "no", label: "Norway" },
  { value: "om", label: "Oman" },
  { value: "pk", label: "Pakistan" },
  { value: "pw", label: "Palau" },
  { value: "ps", label: "Palestinian Territory, Occupied" },
  { value: "pa", label: "Panama" },
  { value: "pg", label: "Papua New Guinea" },
  { value: "py", label: "Paraguay" },
  { value: "pe", label: "Peru" },
  { value: "ph", label: "Philippines" },
  { value: "pn", label: "Pitcairn" },
  { value: "pl", label: "Poland" },
  { value: "pt", label: "Portugal" },
  { value: "pr", label: "Puerto Rico" },
  { value: "qa", label: "Qatar" },
  { value: "re", label: "Reunion" },
  { value: "ro", label: "Romania" },
  { value: "ru", label: "Russian Federation" },
  { value: "rw", label: "Rwanda" },
  { value: "bl", label: "Saint Barthelemy" },
  { value: "sh", label: "Saint Helena" },
  { value: "kn", label: "Saint Kitts and Nevis" },
  { value: "lc", label: "Saint Lucia" },
  { value: "mf", label: "Saint Martin" },
  { value: "pm", label: "Saint Pierre and Miquelon" },
  { value: "vc", label: "Saint Vincent and the Grenadines" },
  { value: "ws", label: "Samoa" },
  { value: "sm", label: "San Marino" },
  { value: "st", label: "Sao Tome and Principe" },
  { value: "sa", label: "Saudi Arabia" },
  { value: "sn", label: "Senegal" },
  { value: "rs", label: "Serbia" },
  { value: "cs", label: "Serbia and Montenegro" },
  { value: "sc", label: "Seychelles" },
  { value: "sl", label: "Sierra Leone" },
  { value: "sg", label: "Singapore" },
  { value: "sx", label: "Sint Maarten" },
  { value: "sk", label: "Slovakia" },
  { value: "si", label: "Slovenia" },
  { value: "sb", label: "Solomon Islands" },
  { value: "so", label: "Somalia" },
  { value: "za", label: "South Africa" },
  { value: "gs", label: "South Georgia and the South Sandwich Islands" },
  { value: "ss", label: "South Sudan" },
  { value: "es", label: "Spain" },
  { value: "lk", label: "Sri Lanka" },
  { value: "sd", label: "Sudan" },
  { value: "sr", label: "Suriname" },
  { value: "sj", label: "Svalbard and Jan Mayen" },
  { value: "sz", label: "Swaziland" },
  { value: "se", label: "Sweden" },
  { value: "ch", label: "Switzerland" },
  { value: "sy", label: "Syrian Arab Republic" },
  { value: "tw", label: "Taiwan, Province of China" },
  { value: "tj", label: "Tajikistan" },
  { value: "tz", label: "Tanzania, United Republic of" },
  { value: "th", label: "Thailand" },
  { value: "tl", label: "Timor-Leste" },
  { value: "tg", label: "Togo" },
  { value: "tk", label: "Tokelau" },
  { value: "to", label: "Tonga" },
  { value: "tt", label: "Trinidad and Tobago" },
  { value: "tn", label: "Tunisia" },
  { value: "tr", label: "Turkey" },
  { value: "tm", label: "Turkmenistan" },
  { value: "tc", label: "Turks and Caicos Islands" },
  { value: "tv", label: "Tuvalu" },
  { value: "ug", label: "Uganda" },
  { value: "ua", label: "Ukraine" },
  { value: "ae", label: "United Arab Emirates" },
  { value: "gb", label: "United Kingdom" },
  { value: "us", label: "United States" },
  { value: "um", label: "United States Minor Outlying Islands" },
  { value: "uy", label: "Uruguay" },
  { value: "uz", label: "Uzbekistan" },
  { value: "vu", label: "Vanuatu" },
  { value: "ve", label: "Venezuela" },
  { value: "vn", label: "Viet Nam" },
  { value: "vg", label: "Virgin Islands, British" },
  { value: "vi", label: "Virgin Islands, U.s." },
  { value: "wf", label: "Wallis and Futuna" },
  { value: "eh", label: "Western Sahara" },
  { value: "ye", label: "Yemen" },
  { value: "zm", label: "Zambia" },
  { value: "zw", label: "Zimbabwe" },
];
